
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  server_port: 443
  base_url: https://crunch.infra.conve.rs:443
  ssl_certificate: /ssl/cert.pem
  ssl_key: /ssl/private.pem

# Text to speech
tts:
  - platform: google_translate

cloud:
  google_actions:
    filter:
      exclude_domains:
        - group
        - media_player
        - automation

mqtt:
  broker: localhost
  discovery: true
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

android_ip_webcam:
  - host: 192.168.86.229
    name: "Living Room Camera"
    switches:
      - torch
      - video_recording
    sensors:

# iOS app
ios:

# HomeKit support
homekit:
  auto_start: false # started after a delay using an automation
  filter:
    exclude_domains:
      - device_tracker
      - person
      - automation

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
