
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  server_port: 443
  base_url: https://crunch.infra.conve.rs:443
  ssl_certificate: /certs/cert.pem
  ssl_key: /certs/private.pem

# Text to speech
tts:
  - platform: google_translate

# Create light wrappers around discovered switches
light:
  - platform: template
    lights:
      living_room_lights:
        friendly_name: 'Living Room Lights'
        level_template: '{{ 100 if is_state("switch.living_room_lights", "on") else 0 }}'
        value_template: '{{ is_state("switch.living_room_lights", "on") }}'
        turn_on:
          service: switch.turn_on
          entity_id: switch.living_room_lights
        turn_off:
          service: switch.turn_off
          entity_id: switch.living_room_lights
        set_level:
          service_template: switch.turn_'{{ "off" if brightness == 0 else "on" }}'
          entity_id: switch.living_room_lights
      kitchen_lights:
        friendly_name: 'Kitchen Lights'
        level_template: '{{ 100 if is_state("switch.kitchen_lights", "on") else 0 }}'
        value_template: '{{ is_state("switch.kitchen_lights", "on") }}'
        turn_on:
          service: switch.turn_on
          entity_id: switch.kitchen_lights
        turn_off:
          service: switch.turn_off
          entity_id: switch.kitchen_lights
        set_level:
          service_template: switch.turn_'{{ "off" if brightness == 0 else "on" }}'
          entity_id: switch.kitchen_lights

cloud:
  google_actions:
    filter:
      exclude_domains:
        - group
        - media_player
      exclude_entities:
        - switch.living_room_lights
        - switch.kitchen_lights

mqtt:
  broker: localhost
  discovery: true
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

android_ip_webcam:
  - host: 192.168.86.229
    name: "Phone Camera"
    sensors:
      - audio_connections
      - battery_level
      - battery_temp
      - battery_voltage
      - light
      - motion
      - pressure
      - proximity
      - sound
      - video_connections
    switches:
      - exposure_lock
      - ffc
      - focus
      - gps_active
      - night_vision
      - overlay
      - torch
      - whitebalance_lock
      - video_recording

# iOS app
ios:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
