
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  server_port: 443
  base_url: https://crunch.infra.conve.rs:443
  ssl_certificate: /certs/cert.pem
  ssl_key: /certs/private.pem

# Text to speech
tts:
  - platform: google_translate

# Create light wrappers around discovered switches
light:
  - platform: template
    lights:
      living_room_lights:
        friendly_name: 'Living Room Lights'
        level_template: '{{ 255 if is_state("switch.living_room_lights", "on") else 0 }}'
        value_template: '{{ is_state("switch.living_room_lights", "on") }}'
        turn_on:
          service: switch.turn_on
          entity_id: switch.living_room_lights
        turn_off:
          service: switch.turn_off
          entity_id: switch.living_room_lights
        set_level:
          service_template: switch.turn_'{{ "off" if brightness == 0 else "on" }}'
          entity_id: switch.living_room_lights

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
