substitutions:
  device_name: living-room-right-window-light
  friendly_name: Living Room Right Window Light
  assigned_ip_address: "192.168.86.209"

packages:
  dimmer_light: !include common/dimmer_light.yaml

mqtt: # needed due to esphome/issues#1487
  broker: !secret mqtt_host
