substitutions:
  device_name: pantry-light
  friendly_name: Pantry Light
  assigned_ip_address: "192.168.86.208"

packages:
  dimmer_light: !include common/dimmer_light.yaml

mqtt: # needed due to esphome/issues#1487
  broker: !secret mqtt_host
